### PR TITLE
Export VaultError. Generate README.md from cargo readme

### PR DESCRIPTION
**Pull request by darlaam**
- Forgot to expose errors (pub use) in last PR.
- README.md generated with cargo readme

### CODE REVIEW

**Comment by darlaam** [comment]
By the way, would it be possible to update the crate on crates.io after the merge ?

**Comment by darlaam** [comment]
@marlonbaeten Up ?

**Comment by darlaam** [comment]
Waow ! Thanks Marlon. 
Is it possible to publish the version to crates.io ?

**Comment by marlonbaeten** [comment]
I do not have the right permissions publish the crate. @Wassasin could you publish the new version?

**Comment by Wassasin** [comment]
Made some minor changes and pushed the update to crates. Thanks!

**Comment by darlaam** [comment]
Thanks a lot !

**Pull request merged**
